// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cubifftzrpaivhvrcevb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN1YmlmZnR6cnBhaXZodnJjZXZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0MTQ4NzQsImV4cCI6MjA1ODk5MDg3NH0.eCC4WxeAq-ktNsppjZwTnVyyHMieZx7P6SLLaVXindU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);